version: "3"

services:
  api:
    container_name: api
    build:
      context: .
      dockerfile: ./docker/api/Dockerfile
    volumes:
      - ./:/go/src/github.com/ulwlu/go-rest
    ports:
      - "8081:1323"
    restart: always
    