version: "3"

services:
  api:
    container_name: api
    build:
      context: .
      dockerfile: ./docker/api/Dockerfile
    ports:
      - "8081:8081"
    restart: always
    networks:
      - go-echo-network
    depends_on:
      - db
    env_file:
      - .env.development

  db:
    container_name: mariadb_db
    build:
      context: .
      dockerfile: ./docker/db/Dockerfile
    ports:
      - "3306:3306"
    networks:
      - go-echo-network
    volumes:
      - ./mysql/init:/docker-entrypoint-initdb.d
      - ./docker/db/conf.d:/etc/mysql/conf.d
    command: --default-authentication-plugin=mysql_native_password
    env_file:
      - .env.development

networks:
  go-echo-network:
    name: go-echo-network
    driver: bridge
    # external: true
